# Generated by Django 4.2.27 on 2025-12-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress_mark', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=models.CASCADE, related_name='logs', to='habits.habit')),
            ],
        ),
    ]
