# Generated by Django 4.2.27 on 2025-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20251224_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitlog',
            old_name='name',
            new_name='habit',
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_e7faa4_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'progress_mark', 'date'], name='habits_habi_habit_i_c5fb76_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unic_habit_date'),
        ),
    ]
